### ISSUE TITLE
Passive scalars behaving incorrectly upon refinement/de-refinement

### ISSUE THREAD

**Issue by atomsite** [PrincetonUniversity/athena#390] opened 2021-09-15 00:07 UTC
I'm having issues with using adaptive mesh refinement in Athena, I have a series of passive scalars in my simulations which begin to break down (jumping rapidly to a very high value and quickly diffusing through the rest of the simulation) as soon as a meshblock is refined, a similar effect is happening when a meshblock is destroyed. It appears that the scalars are not being preserved throughout this process.

I have only added a problem generator for my specific problem, an orbiting colliding wind binary system, and have not made any other changes under the hood.
I've also noticed issues with pressure being higher around the edges of each level boundary, I am unsure what is causing this, but the issue is more defined if a higher order integrator is used.

This passive scalar breakdown is independent of courant number, numerical solver, reconstruction method etc. I've tried nearly every permutation of these I can think of in order to rule that out. The problem is also persistent across different computers, running both G++ and ICPC. This also occurs in single threaded environments as well as multiprocessing environments with either OpenMPI or OpenMP.

I have been using static mesh refinement for my work prior to this, as the systems being simulated have approximately circular orbits, but with these more eccentric orbits AMR is now necessary. Refinement occurs at a set number of cells between the estimated point of the stellar winds colliding, as well as around the stars, this refinement appears to behave as expected, aside from said issues with the scalars.

My problem generator file is below, a series of scalars are added to the simulation through `MeshBlock::UserWorkInLoop` currently there are no other places scalar values are changed.

[cwb.cpp.txt](https://github.com/PrincetonUniversity/athena/files/7165752/cwb.cpp.txt)

I have attached videos of the breakdown occuring, to give a better idea of what is happening:

Density:
https://user-images.githubusercontent.com/16307348/133348841-33089aa6-de56-48e0-8190-266fd7e62c89.mp4
Scalar breaking down:
https://user-images.githubusercontent.com/16307348/133348701-1ff29d58-965e-4258-95a2-b35c3b49b368.mp4
Simulation levels (derived from a scalar, also breaks down for a frame or two before being reset)
https://user-images.githubusercontent.com/16307348/133348769-8a309bb7-2e1d-4e97-bfee-a9c359ccb165.mp4

Thank you!

**Comment by felker** [comment] 2021-09-15 00:15
Thanks for the report; to be clear, it works with SMR and only breaks with AMR? If so, this is a (albeit more extreme) duplicate of #365. Can you post your input file and command line instructions to run the problem? Your problem might be easier for tracking down the bug than @morganemacleod reproducer.

**Closed by felker** 2021-09-15 00:15 UTC
